-- Insert new tags (run this in Supabase SQL Editor)
-- ON CONFLICT akan skip tag yang sudah ada

INSERT INTO tags (name, slug) VALUES
  ('Cinta Beda Dunia', 'cinta-beda-dunia'),
  ('Psikopat', 'psikopat'),
  ('Manja', 'manja'),
  ('Musuh Jadi Cinta', 'musuh-jadi-cinta'),
  ('Werewolf', 'werewolf'),
  ('Cewek Galak', 'cewek-galak'),
  ('Cewek Centil', 'cewek-centil'),
  ('Kepribadian Ganda', 'kepribadian-ganda'),
  ('Alter Ego', 'alter-ego'),
  ('Cinta Beda Agama', 'cinta-beda-agama'),
  ('Setan', 'setan'),
  ('Iblis', 'iblis'),
  ('Introver', 'introver'),
  ('Extrover', 'extrover'),
  ('Dunia Mimpi', 'dunia-mimpi'),
  ('Political Thriller', 'political-thriller'),
  ('Medical Thriller', 'medical-thriller'),
  ('Dystopia', 'dystopia'),
  ('Cloning', 'cloning'),
  ('Game Virtual', 'game-virtual'),
  ('Virtual Reality', 'virtual-reality'),
  ('Gitaris', 'gitaris'),
  ('Kapten Basket', 'kapten-basket'),
  ('Cheerleader', 'cheerleader'),
  ('Cewek Tomboi', 'cewek-tomboi'),
  ('Ketos', 'ketos'),
  ('Anak Band', 'anak-band'),
  ('Cewek Culun', 'cewek-culun'),
  ('Mitos', 'mitos'),
  ('Cowok Culun', 'cowok-culun'),
  ('Kultivasi', 'kultivasi'),
  ('Leveling', 'leveling'),
  ('Kecerdasan Buatan', 'kecerdasan-buatan'),
  ('Ekonomi', 'ekonomi'),
  ('Politik', 'politik'),
  ('Fabel Dewasa', 'fabel-dewasa'),
  ('Anak Berandalan', 'anak-berandalan'),
  ('Oceantwelve', 'oceantwelve'),
  ('Money Heist', 'money-heist'),
  ('Tetangga', 'tetangga'),
  ('Menakutkan', 'menakutkan'),
  ('Romansa Historis', 'romansa-historis'),
  ('Fiksi Sejarah', 'fiksi-sejarah'),
  ('Penyihir', 'penyihir'),
  ('Pejuang', 'pejuang'),
  ('Emosional', 'emosional'),
  ('Posesif', 'posesif'),
  ('Humoris', 'humoris'),
  ('Belahan Jiwa', 'belahan-jiwa'),
  ('Romansa Fantasi', 'romansa-fantasi'),
  ('Angst Rumtang', 'angst-rumtang'),
  ('Konflik Etika', 'konflik-etika'),
  ('Konglomerat', 'konglomerat'),
  ('Idola', 'idola'),
  ('Penggemar', 'penggemar'),
  ('Fanatik', 'fanatik'),
  ('Budaya', 'budaya'),
  ('Selain Manusia', 'selain-manusia'),
  ('Religi Tradisional', 'religi-tradisional'),
  ('Obsesif', 'obsesif'),
  ('Psikologi Thriller', 'psikologi-thriller'),
  ('Crime Thriller', 'crime-thriller'),
  ('Mystery Thriller', 'mystery-thriller'),
  ('Techno Thriller', 'techno-thriller'),
  ('Guna-guna', 'guna-guna'),
  ('Ilmu Hitam', 'ilmu-hitam'),
  ('Ilmu Putih', 'ilmu-putih'),
  ('Mistis', 'mistis'),
  ('Penampakan', 'penampakan'),
  ('Seram', 'seram'),
  ('Dunia Lain', 'dunia-lain'),
  ('Paranormal', 'paranormal'),
  ('Young Adult', 'young-adult'),
  ('Dewasa', 'dewasa'),
  ('Space Travel', 'space-travel'),
  ('Kekayaan', 'kekayaan'),
  ('Jodoh', 'jodoh'),
  ('Fiksi Remaja', 'fiksi-remaja'),
  ('Cinta Satu Malam', 'cinta-satu-malam'),
  ('Mahasiswa', 'mahasiswa'),
  ('Pelajar', 'pelajar'),
  ('Cinta Beda Usia', 'cinta-beda-usia'),
  ('Wanita Tangguh', 'wanita-tangguh'),
  ('Dosen', 'dosen'),
  ('Romansa Kantor', 'romansa-kantor'),
  ('Lucu', 'lucu'),
  ('Bayi Rahasia', 'bayi-rahasia'),
  ('Duda', 'duda'),
  ('Janda', 'janda'),
  ('Percintaan', 'percintaan'),
  ('Kolosal', 'kolosal'),
  ('Sosial', 'sosial'),
  ('Psikologi', 'psikologi'),
  ('Fiksi Ilmiah', 'fiksi-ilmiah'),
  ('Cyber', 'cyber'),
  ('Militer', 'militer'),
  ('Robots', 'robots'),
  ('AI', 'ai'),
  ('Aliens', 'aliens'),
  ('Monster', 'monster'),
  ('Teknologi', 'teknologi'),
  ('Mutan', 'mutan'),
  ('Pedang Sihir', 'pedang-sihir'),
  ('Konflik Rumtang', 'konflik-rumtang'),
  ('Malebook', 'malebook'),
  ('Femalebook', 'femalebook'),
  ('Pengacara', 'pengacara'),
  ('Kehidupan', 'kehidupan'),
  ('Dokter', 'dokter'),
  ('Kegelisahan', 'kegelisahan'),
  ('Alam Gaib', 'alam-gaib'),
  ('Hantu', 'hantu'),
  ('Santet', 'santet'),
  ('Dukun', 'dukun'),
  ('Action', 'action'),
  ('Adventure', 'adventure'),
  ('Comedy', 'comedy'),
  ('Drama', 'drama'),
  ('Fantasi', 'fantasi'),
  ('Horror', 'horror'),
  ('Mystery', 'mystery'),
  ('Romansa', 'romansa'),
  ('Sci-fi', 'sci-fi'),
  ('Thriller', 'thriller'),
  ('Chicklit', 'chicklit'),
  ('Teenlit', 'teenlit'),
  ('Apocalypse', 'apocalypse'),
  ('Pernikahan', 'pernikahan'),
  ('Sistem', 'sistem'),
  ('Urban', 'urban'),
  ('Fanfiction', 'fanfiction'),
  ('Religi', 'religi'),
  ('Suspense', 'suspense'),
  ('Pembunuhan', 'pembunuhan'),
  ('Legenda', 'legenda'),
  ('Perkotaan', 'perkotaan'),
  ('Modern', 'modern'),
  ('Gangster', 'gangster'),
  ('Geng Motor', 'geng-motor')
ON CONFLICT (name) DO NOTHING;

-- Check total tags after insert
SELECT COUNT(*) as total_tags FROM tags;
