import { createClient } from '@supabase/supabase-js';
import Constants from 'expo-constants';

// Get Supabase credentials from environment
const supabaseUrl = Constants.expoConfig?.extra?.NEXT_PUBLIC_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = Constants.expoConfig?.extra?.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase credentials! Make sure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY are set in Replit Secrets.');
}

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});

// Database types (auto-generated by Supabase, but we define manually for now)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: number;
          email: string;
          name: string;
          is_writer: boolean;
          coin_balance: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          email: string;
          name: string;
          is_writer?: boolean;
          coin_balance?: number;
        };
        Update: {
          email?: string;
          name?: string;
          is_writer?: boolean;
          coin_balance?: number;
        };
      };
      novels: {
        Row: {
          id: number;
          title: string;
          author: string;
          author_id: number | null;
          genre: string;
          description: string;
          cover_url: string | null;
          status: string;
          rating: number;
          total_chapters: number;
          free_chapters: number;
          chapter_price: number;
          total_reads: number;
          created_at: string;
          updated_at: string;
        };
      };
      chapters: {
        Row: {
          id: number;
          novel_id: number;
          chapter_number: number;
          title: string;
          content: string;
          word_count: number;
          is_free: boolean;
          price: number;
          published_at: string;
          created_at: string;
          updated_at: string;
        };
      };
      reading_progress: {
        Row: {
          id: number;
          user_id: number;
          novel_id: number;
          chapter_id: number;
          progress: number;
          last_read_at: string;
        };
      };
      unlocked_chapters: {
        Row: {
          id: number;
          user_id: number;
          chapter_id: number;
          novel_id: number;
          unlocked_at: string;
        };
      };
      following_novels: {
        Row: {
          id: number;
          user_id: number;
          novel_id: number;
          followed_at: string;
        };
      };
      coin_transactions: {
        Row: {
          id: number;
          user_id: number;
          amount: number;
          type: string;
          description: string | null;
          metadata: any;
          created_at: string;
        };
      };
    };
  };
}
